### ISSUE TITLE
JEasyOpc,组态王6.53 读取字符串乱码

### ISSUE THREAD

**Issue by sunzhenqing** [luoyan35714/OPC_Client#1]
使用 SynchReadItemExample类,读取组态王里面的字符串类型汉字是乱码.
有遇到过么.

**Comment by sunzhenqing** [comment]
String val = responseItem.getValue().toString();
new String(val.getBytes("iso8859-1"),"gbk");
例子没问题.

**Comment by luoyan35714** [comment]
没遇到过你说的问题，我用Eclipse的时候编码是UTF-8，是这个原因么

**Comment by luoyan35714** [comment]
@sunzhenqing 没遇到过你说的问题，我用Eclipse的时候编码是UTF-8，是这个原因么

**Comment by sunzhenqing** [comment]
我在组态王中设置一个内存字符串,
当我用图形界面填写入一个"我"字是,通过SynchReadItemExample 和new String可以读取到正确的"我"
但是当我填写"我的的"或其他文字是,通过SynchReadItemExample 和new String 读取的数据就是乱码.
假如用SynchWrite写入内存字符串中的. 在使用SynchRead读取的时候是正确的汉字.但是这时候写入的内容通过图形界面查看的话是乱码.
我也不清楚跟我的xp有没有关系.或者我的eclipse有关系.
