### ISSUE TITLE
Can't load IA 32-bit .dll on a AMD 64-bit platform

### ISSUE THREAD

**Issue by lhf552004** [luoyan35714/OPC_Client#2]
Hi,你好，感谢你的代码，我在运行OPC_Client_JeasyOPC项目的时候，报了一个错，说是32bit.dll不兼容64位的电脑，请问你有64位的dll吗

![image](https://user-images.githubusercontent.com/10030850/30019346-cd22d29e-9192-11e7-9348-1a018e9000e4.png)

**Comment by lhf552004** [comment]
重新下载了好了。

**Comment by luoyan35714** [comment]
看报错的原因是我项目提供的dll文件是32位操作系统编译出来的。而你的运行环境是64位的。好久没有用OPC了，你可以Google下看看有没有64位的官方DLL提供。
