### ISSUE TITLE
你好，不知道utgard SyncAccess一次性读取太多item会无返回的现象有没有遇到过？

### ISSUE THREAD

**Issue by abcfy2** [luoyan35714/OPC_Client#3]
大致的代码如下：

```java
tagList.foreach({tag -> {
    access.addItem(tag, (Item item, ItemState state) -> {
            System.out.println(state.toString());
    }
}});

access.bind();
```

在tag点比较少的时候没什么问题(80个以内)，在tag点多的时候`access.bind()`之后就没反应了。看DEBUG日志也把item给激活了，能看到所有的tag点都有这样的日志：

```
2017-11-03 09:47:26,566 DEBUG org.openscada.opc.lib.da.AccessBase - Realizing item: [DKZC4]DZB6[137]
2017-11-03 09:47:26,586 DEBUG org.openscada.opc.lib.da.Item - Adding new item '[DKZC4]DZB6[137]' (0x1188E4A0) for group org.openscada.opc.lib.da.Group@3726d7c5
2017-11-03 09:47:26,586 DEBUG org.openscada.opc.lib.da.Group - Adding item: '[DKZC4]DZB6[137]', 294184096
```

我分析了下源码，这里应该是没问题的，都成功通过DCOM连接到opc server了，并且将group和item都设置为active，但是量一大就没有任何返回，不知道朋友你遇到过吗？

**Comment by luoyan35714** [comment]
没有遇到过，不过我们是分的20个一组来获取的，防止在某次采集的时候由于网络原因导致大量点无法采集。

**Comment by abcfy2** [comment]
非常感谢解答。我这边还有个问题，就是没法用异步订阅的方式获取item(`Async20Access`)

上面的代码用`SyncAccess`执行没有任何问题，仅仅将`AccessBase`实例换成了`Async20Access`，就会报错：

```
 ERROR org.openscada.opc.lib.da.AccessBase - Failed to change state (true)
org.jinterop.dcom.common.JIException: The RPC server is unavailable. Please check if the COM server is up and running and that route to the COM Server is accessible (A simple "Ping" to the Server machine would do). Also please confirm if the Windows Firewall is not blocking DCOM access. [0x800706BA]
```

我在google上搜了下，和这个问题一模一样
 https://groups.google.com/forum/#!topic/openscada/wuIAnkrEhKQ

都是ubuntu连接windows上的opc server。后来把代码迁移到windows下，发现也是完全相同的问题，无从下手，不知道 @luoyan35714 遇到过么？多谢

**Comment by luoyan35714** [comment]
@abcfy2 把防火墙关了试下呢？我当时遇到过如果开着防火墙OPC会连接失败的异常。

**Comment by mlyknown** [comment]
> 非常感谢解答。我这边还有个问题，就是没法用异步订阅的方式获取item(`Async20Access`)
> 
> 上面的代码用`SyncAccess`执行没有任何问题，仅仅将`AccessBase`实例换成了`Async20Access`，就会报错：
> 
> ```
>  ERROR org.openscada.opc.lib.da.AccessBase - Failed to change state (true)
> org.jinterop.dcom.common.JIException: The RPC server is unavailable. Please check if the COM server is up and running and that route to the COM Server is accessible (A simple "Ping" to the Server machine would do). Also please confirm if the Windows Firewall is not blocking DCOM access. [0x800706BA]
> ```
> 我在google上搜了下，和这个问题一模一样
> https://groups.google.com/forum/#!topic/openscada/wuIAnkrEhKQ
> 
> 都是ubuntu连接windows上的opc server。后来把代码迁移到windows下，发现也是完全相同的问题，无从下手，不知道 @luoyan35714 遇到过么？多谢
你好，这个问题解决了吗？

**Comment by abcfy2** [comment]
解决了。当时因为是跨网络使用VPN访问的OPC服务器，发现是VPN网卡的MTU设置有问题(openvpn默认的设置好像是1400还是什么的，忘了)，和目标VPN服务器的网卡MTU不符，修改MSS改为1420好像就好了，参见: https://www.sonassi.com/help/troubleshooting/setting-correct-mtu-for-openvpn
