### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by helloaaaaa** [luoyan35714/OPC_Client#4]
本地 装了KEPserver6.5 , org.openscada.opc.dcom工程下的
![image](https://user-images.githubusercontent.com/40763100/53786539-fca63880-3f56-11e9-8bf7-3d3d79f27a7c.png)  没清楚这块的配置

**Comment by luoyan35714** [comment]
org.openscada.opc.dcom.test
org.openscada.opc.dcom
org.openscada.opc.lib.test
org.openscada.opc.lib

这四个项目的配置都不需要改，因为这只是需要引入的官方jar包，而我把他们的代码拷贝下来而已
