### ISSUE TITLE
opcda问题询问

### ISSUE THREAD

**Issue by lishuaia** [luoyan35714/OPC_Client#5]
您好，我在linux系统上运行DCOMTest程序都没有运行起来，都报错：The RPC server is unavailable. Please check if the COM server is up and running and that route to the COM Server is accessible (A simple "Ping" to the Server machine would do). Also please confirm if the Windows Firewall is not blocking DCOM access. [0x800706BA]，你知道这是为什么吗？

**Comment by luoyan35714** [comment]
Linux中串口不是COM了。是/dev/ttyS*
可以参考下这篇文章
https://www.hifreud.com/2016/03/03/linux-serial-port/

**Comment by lishuaia** [comment]
您好，我看了你给我发的资料，但是我在代码有没有找到填写串口的地方啊，您能再指导下我吗

**Comment by luoyan35714** [comment]
这个是OPC啊，抱歉，我想成串口的MODBUS协议了。Linux下的OPC我也没弄过。抱歉哈
